version: "3.9"
networks:
  laravel:
services:
  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    ports: 
    - "9443:80"
    volumes:
      - "./:/var/www/html"
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - laravel
    expose:
      - 9443
  mysql:
    image: mysql:8
    container_name: laravel_mysql
    ports:
      - "33066:3306"
    volumes:
      - "./mysql:/var/lib/mysql"
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: dbtest
      MYSQL_ROOT_PASSWORD: root
      MYSQL_SERVICE_NAME: mysql
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: DockerFile
    container_name: laravel_php
    ports:
      - "9000:9000"
    volumes:
      - "./:/var/www/html"
    networks:
      - laravel
